version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ringle_app
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/ringle_task_development
      - REDIS_URL=redis://redis:6379/0
      - SIDEKIQ_REDIS_URL=redis://redis:6379/1
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DOCKER_ENV=true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: sh -c "bundle install && bundle exec rails db:prepare && bundle exec rails server -b 0.0.0.0"

  postgres:
    image: postgres:15-alpine
    container_name: ringle_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ringle_task_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ringle_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ringle_sidekiq
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/0
      - SIDEKIQ_REDIS_URL=redis://redis:6379/1
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/ringle_task_development
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DOCKER_ENV=true
    command: sh -c "bundle install && bundle exec sidekiq -e development -q critical,3 -q default,2"
    depends_on:
      app:
        condition: service_started
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  bundle_cache:
  
