FROM ruby:3.2-alpine

# 개발용 패키지 설치
RUN apk add --no-cache \
    build-base \
    postgresql-dev \
    postgresql-client \
    tzdata \
    curl \
    git \
    bash

WORKDIR /app

# bundler 설정
RUN gem install bundler

# 포트 노출
EXPOSE 3001

# 개발 서버 실행을 위한 기본 명령어
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
